//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNetStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int Id { get; set; }
        public int clientId { get; set; }
        public string productId { get; set; }
        public string productName { get; set; }
        public Nullable<int> cpQuantity { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
