//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCNetStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int clientId { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal totalPrice { get; set; }
        public string orderStatus { get; set; }
    
        public virtual client client { get; set; }
    }
}
